import logging
from utils.llm_utils import get_llm, get_fallback_llm

logger = logging.getLogger(__name__)

_DISCLAIMER = (
    "\n\n**Important Disclaimer:** This report is generated by an AI system for "
    "informational purposes only. It does not constitute medical advice, diagnosis, "
    "or treatment. Always consult a qualified healthcare professional before making "
    "any medical decisions."
)


def synthesis_node(state):
    """
    Node: Synthesizes all upstream findings into a coherent, patient-friendly report.
    Includes abnormal AND noteworthy normal findings, urgency context, and AI disclaimer.
    """
    validated = state.validated_params or {}
    patterns = state.patterns or []
    risk = state.risk_assessment or {}
    context = state.context_analysis or {}
    patient_info = state.patient_info or {}
    interpreted = state.param_interpretation or {}

    if not validated:
        return {"synthesis_report": "No laboratory data available to synthesize." + _DISCLAIMER}

    # Build abnormal findings with severity
    abnormal_lines = []
    normal_lines = []
    critical_lines = []

    for param, info in interpreted.items():
        status = info.get("status", "unknown")
        severity = info.get("severity", "unknown")
        val = info.get("value")
        unit = info.get("unit", "")
        ref = info.get("reference", {})
        ref_str = f"(ref: {ref.get('low')}-{ref.get('high')} {unit})" if ref else ""

        if info.get("is_critical"):
            critical_lines.append(f"  ⚠ CRITICAL — {param}: {val} {unit} {ref_str}")
        elif status in ("low", "high"):
            abnormal_lines.append(f"  {param}: {val} {unit} [{status.upper()}, {severity}] {ref_str}")
        else:
            normal_lines.append(f"  {param}: {val} {unit} [NORMAL]")

    critical_block = "\n".join(critical_lines) if critical_lines else "  None"
    abnormal_block = "\n".join(abnormal_lines) if abnormal_lines else "  None"
    normal_count = len(normal_lines)
    patterns_block = "\n  ".join(patterns) if patterns else "  No clinical patterns detected"
    urgency = context.get("urgency", "routine")
    risk_score = risk.get("score", "N/A")
    risk_rationale = risk.get("rationale", [])
    rationale_str = "\n  ".join(risk_rationale) if isinstance(risk_rationale, list) else str(risk_rationale)
    context_analysis = context.get("analysis", "Not available")
    adjusted_concerns = context.get("adjusted_concerns", "None noted")

    patient_line = (
        f"Patient: {patient_info.get('Name', 'Anonymous')} | "
        f"Age: {patient_info.get('Age', 'Unknown')} | "
        f"Gender: {patient_info.get('Gender', 'Unknown')}"
    )

    prompt = f"""You are an AI medical report writer producing a professional CBC analysis report for a patient.
Write in clear, empathetic, layperson-friendly language while maintaining medical accuracy.

═══════════════════════════════════════
PATIENT INFORMATION
═══════════════════════════════════════
{patient_line}

═══════════════════════════════════════
CRITICAL ALERTS
═══════════════════════════════════════
{critical_block}

═══════════════════════════════════════
ABNORMAL FINDINGS
═══════════════════════════════════════
{abnormal_block}

═══════════════════════════════════════
NORMAL PARAMETERS ({normal_count} values within range)
═══════════════════════════════════════
(These are reassuring findings — acknowledge them.)

═══════════════════════════════════════
CLINICAL PATTERNS IDENTIFIED
═══════════════════════════════════════
  {patterns_block}

═══════════════════════════════════════
RISK ASSESSMENT
═══════════════════════════════════════
Overall Risk Score : {risk_score}/10
Urgency Level      : {urgency.upper()}
Rationale:
  {rationale_str}

═══════════════════════════════════════
CONTEXTUAL ANALYSIS
═══════════════════════════════════════
{context_analysis}

Adjusted Concerns:
{adjusted_concerns}

═══════════════════════════════════════
REPORT WRITING RULES (STRICT)
═══════════════════════════════════════
1. Start with a brief opening that states the overall picture (reassuring or concerning).
2. Explain each CRITICAL alert first (if any), in plain language, including why it matters.
3. Explain ABNORMAL findings with context — what they mean for THIS patient.
4. Briefly acknowledge normal findings to provide balance and reassurance.
5. Summarise the clinical patterns and what they suggest overall.
6. Close with urgency-appropriate next steps:
   - routine: "Consider routine follow-up with your doctor."
   - follow-up: "Schedule a follow-up appointment within 4-6 weeks."
   - prompt: "Please see your doctor within the next week."
   - urgent: "Please seek medical attention promptly — do not delay."
7. Use **bold** for key parameter names and findings.
8. Do NOT use # or ## headers. Use **Bold** for section titles instead.
9. Do NOT use horizontal rules (---).
10. Be concise — 250-400 words total.
11. Do NOT sign as a doctor or medical professional.
12. Do NOT make definitive diagnoses.
"""

    try:
        llm = get_llm()
        response = llm.invoke(prompt)
        report = response.content.strip() if hasattr(response, "content") else str(response).strip()
        logger.info(f"synthesis: report generated, urgency={urgency}, risk={risk_score}")
        return {"synthesis_report": report + _DISCLAIMER}

    except Exception as e:
        logger.warning(f"synthesis primary model failed: {e}. Trying fallback.")
        try:
            llm = get_fallback_llm()
            response = llm.invoke(prompt)
            report = response.content.strip() if hasattr(response, "content") else str(response).strip()
            return {"synthesis_report": report + _DISCLAIMER}
        except Exception as e2:
            logger.error(f"synthesis fallback also failed: {e2}")
            return {"errors": state.errors + [f"Synthesis Node failed: {str(e2)}"]}
